### ISSUE TITLE
Rework either GA or BT to use same exact file for reading puzzles

### ISSUE THREAD

**Issue by GrandDukeNick** [danielshamsudin/TDA#4]
The unfilled cells of the puzzle are denoted with '-' for Sudoku input files in the case of GA , while backtracking uses '0'. Could try to make this process uniform if possible

**Comment by danielshamsudin** [comment]
Think better modify on backtracking since I dont want to spend time messing with GA's code

**Comment by danielshamsudin** [comment]
Fixed, refer to latest commit on branch Backtracking.
